### ISSUE TITLE
docker exec -it dm-ticket dm-ticket出现超时

### ISSUE THREAD

**Issue by yukmingyu** [ClassmateLin/dm-ticket#128]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:31:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xiaoyudesu** [comment]
一样如此

**Comment by yukmingyu** [comment]
![image](https://github.com/ClassmateLin/dm-ticket/assets/134665788/83fb33b3-4529-4391-9ecd-8a37ddc7da09)
![image](https://github.com/ClassmateLin/dm-ticket/assets/134665788/8b0fd68e-b435-477c-b8b6-d6444e35f2e0)
ji'shi即使去掉8080也没用

**Comment by karhank** [comment]
+1 同样的问题，容器在运行ping完几个ip返回也没问题，运行dm-login也一样超时

**Comment by lxac** [comment]
`~/dm-ticket$ docker exec -it dm-ticket dm-ticket
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (https://mtop.damai.cn/h5/mtop.damai.wireless.search.broadcast.list/1.0/?): error trying to connect: dns error: failed to lookup address information: Try again

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again', src/bin/ticket.rs:31:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

`~/dm-ticket$ docker exec -it dm-ticket dm-login
 INFO  dm_ticket::login > 正在获取二维码...

 ERROR dm_ticket::login > Fail to get qrcode data, error:error sending request for url (https://ipassport.damai.cn/newlogin/qrcode/generate.do?_bx-v=2.5.0&_csrf_token=ssISdcn1wJsAJHCaJHKDn&appEntrance=damai&appName=damai&bizParams=&bx-ua=225%21yaz3xpzWooi%2B%2Fvh9noSozp7Xi%2BljrqtQokHIHC3pAbWYgAsC4CKo%2ByGO6DJvKjEsJM0l%2Bv1BP%2BGiTtXkDHbFXwthnrSDY33Uv9ZRQ3rsnAvNnpTgEM3QHHzaItLksK03ID7Lv00rjWMbP9fwXLi0%2BWooQzadD654fodCbU4KjcI4%2ByYTbkZW8hulQE9dDMXhfikTomTjcLmyJ4bRDl%2F%2Bf4joQzaKD6541izmb3qg2B5dLhDV%2Fm%2B4sxwoQzaKD75hfodlbU4KRMlYoJiRDl%2Fzfej0Qz0KDM53uodCRGNw9gJvXMiiSNyk2VWllCU2SP2QI1%2BVU%2BhOwAm0SV4abvJD86uqCUDNH8kqfIHLoF08B8IonVY%2Fgzr8M6SO1pYu%2FXEPRRmUUKSNqsvVXnTLgtvBM4QGCjQ6h8EPuz5vbZTdjxf4oLijDl%2FyRb30QE0KDG22Qsb%2BUiTgziO%2FVKhDRzJDf%2FPTmhiMqjVesVWbIGuJexFVqEqdGXLlUP0G5%2B%2BjIM0T3IpYN%2BvYwedfckFf%2F4yTR30ukshN5qzcXEBDrE3kAC87Raq2irp91vNp9XdrGKafJm2SNiTo%2B4jofpAMX487NmHt%2By%2BNAwKIopCgU1qhBRdya0Fu%2FJBVsYNFHgYfE%2FXDDkNng2p2LoG6lzqkRcadwHkREzK4MoD64T9c%2FSNnu00uHtg0e00M7Pr2eqBIM6FbbUoP4wSibR02T4RC%2BeRdXRtsVwN%2FZE5vFqaFB3gM%2F50cBl2jE1e3ySiSUgguHeeqGLk3iDVtlupQtbQTV59GIqK07iJvkQvVnHpXyW0nPdHnAzPpMeLVxnXzcDo0IApXz1gpSRmJMeQverqBgIhjTPjZpefgYAfjgLp%3D&bx-umidtoken=G324EE6A9D2542774BA38ADD034DC6548457F8C4E682E1461B7&fromSite=18&hsiz=65d2b44d5d23a3bc32c763c8134aeb31&isMobile=false&lang=zh_CN&returnUrl=https%3A%2F%2Fpassport.damai.cn%2Fdologin.htm%3FredirectUrl%3Dhttps%25253A%25252F%25252Fwww.damai.cn%25252F%26platform%3D106002&umidTag=SERVER&umidToken=9g3v50ukv96blfygup5weibe5g470dwfbgcvkcm5): error trying to connect: dns error: failed to lookup address information: Try again

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again
Error: error sending request for url (https://ipassport.damai.cn/newlogin/qrcode/generate.do?_bx-v=2.5.0&_csrf_token=ssISdcn1wJsAJHCaJHKDn&appEntrance=damai&appName=damai&bizParams=&bx-ua=225%21yaz3xpzWooi%2B%2Fvh9noSozp7Xi%2BljrqtQokHIHC3pAbWYgAsC4CKo%2ByGO6DJvKjEsJM0l%2Bv1BP%2BGiTtXkDHbFXwthnrSDY33Uv9ZRQ3rsnAvNnpTgEM3QHHzaItLksK03ID7Lv00rjWMbP9fwXLi0%2BWooQzadD654fodCbU4KjcI4%2ByYTbkZW8hulQE9dDMXhfikTomTjcLmyJ4bRDl%2F%2Bf4joQzaKD6541izmb3qg2B5dLhDV%2Fm%2B4sxwoQzaKD75hfodlbU4KRMlYoJiRDl%2Fzfej0Qz0KDM53uodCRGNw9gJvXMiiSNyk2VWllCU2SP2QI1%2BVU%2BhOwAm0SV4abvJD86uqCUDNH8kqfIHLoF08B8IonVY%2Fgzr8M6SO1pYu%2FXEPRRmUUKSNqsvVXnTLgtvBM4QGCjQ6h8EPuz5vbZTdjxf4oLijDl%2FyRb30QE0KDG22Qsb%2BUiTgziO%2FVKhDRzJDf%2FPTmhiMqjVesVWbIGuJexFVqEqdGXLlUP0G5%2B%2BjIM0T3IpYN%2BvYwedfckFf%2F4yTR30ukshN5qzcXEBDrE3kAC87Raq2irp91vNp9XdrGKafJm2SNiTo%2B4jofpAMX487NmHt%2By%2BNAwKIopCgU1qhBRdya0Fu%2FJBVsYNFHgYfE%2FXDDkNng2p2LoG6lzqkRcadwHkREzK4MoD64T9c%2FSNnu00uHtg0e00M7Pr2eqBIM6FbbUoP4wSibR02T4RC%2BeRdXRtsVwN%2FZE5vFqaFB3gM%2F50cBl2jE1e3ySiSUgguHeeqGLk3iDVtlupQtbQTV59GIqK07iJvkQvVnHpXyW0nPdHnAzPpMeLVxnXzcDo0IApXz1gpSRmJMeQverqBgIhjTPjZpefgYAfjgLp%3D&bx-umidtoken=G324EE6A9D2542774BA38ADD034DC6548457F8C4E682E1461B7&fromSite=18&hsiz=65d2b44d5d23a3bc32c763c8134aeb31&isMobile=false&lang=zh_CN&returnUrl=https%3A%2F%2Fpassport.damai.cn%2Fdologin.htm%3FredirectUrl%3Dhttps%25253A%25252F%25252Fwww.damai.cn%25252F%26platform%3D106002&umidTag=SERVER&umidToken=9g3v50ukv96blfygup5weibe5g470dwfbgcvkcm5): error trying to connect: dns error: failed to lookup address information: Try again

Caused by:
    0: error trying to connect: dns error: failed to lookup address information: Try again
    1: dns error: failed to lookup address information: Try again
    2: failed to lookup address information: Try again`

一样的问题

**Comment by shenxinde** [comment]
解决了吗

**Comment by xiaoyudesu** [comment]
看 #124
