### ISSUE TITLE
请求url超时有人遇到这个问题吗(http://172.88.0.2:8080/?key=bx_token): operation timed out

### ISSUE THREAD

**Issue by shenxinde** [ClassmateLin/dm-ticket#135]
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): operation timed out

Caused by:
    operation timed out', src/bin/ticket.rs:31:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by xiaoyudesu** [comment]
#124

**Comment by Leehom0512** [comment]
> #124

重启了也还是不行耶我的

**Comment by JK-Solution** [comment]
> > #124
> 
> 重启了也还是不行耶我的

Ping的通，但会超时

**Comment by PeterChan10** [comment]
重启 卸载重装了还是这个问题

**Comment by Jeremy0309** [comment]
` dm-ticket docker exec -it dm-ticket dm-ticket
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: error sending request for url (http://172.88.0.2:8080/?key=bx_token): error trying to connect: tcp connect error: Network unreachable (os error 101)

Caused by:
    0: error trying to connect: tcp connect error: Network unreachable (os error 101)
    1: tcp connect error: Network unreachable (os error 101)
    2: Network unreachable (os error 101)', src/bin/ticket.rs:31:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`


同问
